export const GET_BRANCHES = "GET_BRANCHES";
export const SET_BRANCHES = "SET_BRANCHES";
export const SET_BRANCHES_LOADING = "SET_BRANCHES_LOADING";
export const ENABLE_BRANCHES_RESERVATIONS = "ENABLE_BRANCHES_RESERVATIONS";
export const DISABLE_RESERVATIONS = "DISABLE_RESERVATIONS";
export const UPDATE_BRANCH_SETTINGS = "UPDATE_BRANCH_SETTINGS";
export const DISABLE_BRANCH_RESERVATIONS = "DISABLE_BRANCH_RESERVATIONS";
