export const GET_BRANCHES = "GET_BRANCHES";
export const SET_BRANCHES = "SET_BRANCHES";
export const SET_BRANCHES_LOADING = "SET_BRANCHES_LOADING";
export const ENABLE_BRANCH_RESERVATIONS = "ENABLE_BRANCH_RESERVATIONS";
